version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "tuesday"
    time: "07:00"
    timezone: "Europe/Zurich"
  groups:
    dev-dependencies:
      patterns:
        - "chai"
        - "eslint"
        - "js-yaml"
        - "mocha"
        - "nodemon"
        - "nyc"
        - "puppeteer"
        - "puppeteer-to-istanbul"
        - "sequelize-cli"
        - "sinon"
        - "supertest"
        - "eslint-output"
        - "run-script-os"
        - "supertest"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
  reviewers:
      - "Ehevi"
      - "xsalonx"
