
services:
  application:
    build: 
      target: development
    ports:
      - target: 8081
        published: 8081

    volumes:
      - type: bind
        read_only: false
        source: ./app
        target: /opt/RunConditionTable/app

    restart: "no"

  database:
    build: 
      target: development
    environment:
      - MOCK_DB=true

    restart: "no"