services:
<<<<<<< HEAD
    application:
        build:
            target: test
        volumes:
            - type: bind
              read_only: false
              source: ./reports
              target: /opt/RunConditionTable/reports

        restart: 'no'
=======
  application:
    build: 
      target: test
    volumes:
      - type: bind
        read_only: false
        source: ./reports
        target: /opt/RunConditionTable/reports
        
    restart: "no"
>>>>>>> master

    database:
        build:
            target: test
        environment:
            - MOCK_DB=true

        restart: 'no'
