
services:
  application:
    build: 
      target: development
    environment:
      - ENV_MODE=dev

    volumes:
      - type: bind
        read_only: false
        source: ./app
        target: /opt/RunConditionTable/app
      - type: bind
        read_only: true
        source: ./scripts
        target: /opt/RunConditionTable/scripts
      - type: bind
        read_only: true
        source: ./package.json
        target: /opt/RunConditionTable/package.json
      - type: bind
        read_only: true
        source: ./package-lock.json
        target: /opt/RunConditionTable/package-lock.json
    

    restart: "no"

  database:
    build: 
      target: development
    environment:
      - MOCK_DB=${MOCK_DB:-true}
      - ENV_MODE=dev

    restart: "no"