FROM postgres:14.2-bullseye as base

    WORKDIR /postgres/run

    RUN apt update -y
    RUN apt install -y \
        bash \
        sudo \
        procps

    ENV POSTGRES_PASSWORD=postgres
    ENV POSTGRES_USER=postgres
    ENV POSTGRES_DB=postgres
    ENV PGDATA=/var/lib/postgresql/data/pgdata
    ENV POSTGRES_HOST_AUTH_METHOD=md5


FROM base as development
FROM base as test
FROM base as production






