services:
  application:
    build:
      context: ./
      dockerfile: Dockerfile.application
    environment:
      - RUNNING_ENV=DOCKER
    
  
  database:
    build: 
      context: ./
      dockerfile: Dockerfile.database
    environment:
      - RUNNING_ENV=DOCKER
