services:
    application:
        build:
            target: development

        volumes:
            - type: bind
              read_only: false
              source: ./app
              target: /opt/RunConditionTable/app
        environment:
            - CERN_SOCKS=${CERN_SOCKS:?'you must specify how your are going to use CERN_SOCKS, see main README'}

        restart: 'no'

    database:
        build:
            target: development
        environment:
            - MOCK_DB=true

        restart: 'no'
