
services:
  o2-rct_application:
    build: 
      target: test
    env_file:
      - ./docker/env_file-test
    volumes:
      - type: bind
        read_only: false
        source: ./reports
        target: /opt/RunConditionTable/reports
        
    restart: "no"

  o2-rct_database:
    build: 
      target: test
    env_file:
      - ./docker/env_file-test

    
    restart: "no"