services:
  application:
    build:
      context: ../
      dockerfile: docker/Dockerfile.application
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - rct-network
    volumes:
      - type: bind
        read_only: true
        source: ../security
        target: /opt/RunConditionTable/security
    
  database:
    build: 
      context: ../
      dockerfile: docker/Dockerfile.database
    environment:
      - RUNNING_ENV=DOCKER
    volumes:
      - type: bind
        read_only: true
        source: ../database
        target: /docker-entrypoint-initdb.d
    networks:
      - rct-network
networks:
  rct-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.200.200.0/24"
          gateway: "172.200.200.1"
      


