version: '3.1'
services:
  o2-rct_application:
    container_name: o2-rct_application
    stdin_open: true
    tty: true 
    build:
      context: ./
      dockerfile: docker/Dockerfile.application
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - o2-rct_network
    volumes:
      - type: bind
        read_only: true
        source: ./security
        target: /opt/RunConditionTable/security
    
  o2-rct_database:
    container_name: o2-rct_database
    build: 
      context: ./
      dockerfile: docker/Dockerfile.database
    environment:
      - RUNNING_ENV=DOCKER
    volumes:
      - type: bind
        read_only: false
        source: ./database
        target: /docker-entrypoint-initdb.d
    networks:
      - o2-rct_network
networks:
  o2-rct_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.200.200.0/24"
          gateway: "172.200.200.1"
      


