version: '3.1'
services:
  application:
    volumes:
      - type: bind
        read_only: true
        source: ./app
        target: /opt/RunConditionTable/app
      - type: bind
        read_only: false
        source: ./app/public/ # must be directory due to read_only flag conflict with previous bind
        target: /opt/RunConditionTable/app/public/
      - type: bind
        read_only: true
        source: ./scripts
        target: /opt/RunConditionTable/scripts
      - type: bind
        read_only: true
        source: ./package.json
        target: /opt/RunConditionTable/package.json
      - type: bind
        read_only: true
        source: ./package-lock.json
        target: /opt/RunConditionTable/package-lock.json
    
  database:
    volumes:
      - type: bind
        read_only: true
        source: ./database
        target: /docker-entrypoint-initdb.d
