version: '3.1'
services:
  application:
    container_name: $APP_CONTAINER_NAME
    working_dir: /opt/RunConditionTable
    command: ["./scripts/check-host-and-exec.sh", "$DB_CONTAINER_NAME", "5432", "10", "--", "npm", "run", "start:$TARGET"]
    stdin_open: true
    tty: true 
    build:
      context: ./
      dockerfile: docker/application.dockerfile
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - network

  database:
    container_name: $DB_CONTAINER_NAME 
    working_dir: /postgres/run
    build: 
      context: ./
      dockerfile: docker/database.dockerfile
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - network
  
      


