
services:
  application:
    restart: "no"
    volumes:
      - type: bind
        read_only: false
        source: ./reports
        target: /opt/RunConditionTable/reports
        bind:
          create_host_path: true
        
  database:
    restart: "no"

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.200.202.0/24"
          gateway: "172.200.202.1"