version: '3.1'
services:
  o2-rct_application:
    container_name: o2-rct_application-$TARGET
    stdin_open: true
    tty: true 
    build:
      context: ./
      dockerfile: docker/application.dockerfile
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - o2-rct_network

  o2-rct_database:
    container_name: o2-rct_database-$TARGET
    build: 
      context: ./
      dockerfile: docker/database.dockerfile
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - o2-rct_network
  
      


