
services:
  application:
    build: 
      target: test
    environment:
      - ENV_MODE=test
    volumes:
      - type: bind
        read_only: false
        source: ./reports
        target: /opt/RunConditionTable/reports
        
    restart: "no"

  database:
    build: 
      target: test
    environment:
      - MOCK_DB=true
      - ENV_MODE=test

    
    restart: "no"