FROM postgres:14.2-bullseye as base

    WORKDIR /postgres/run

    RUN apt update -y
    RUN apt install -y \
        bash \
        sudo \
        procps

FROM base as development
    RUN apt install -y inotify-tools

FROM base as test
FROM base as production






