
services:
  o2-rct_application:
    build: 
      target: development
    env_file:
    - ./docker/dev.env
    
    ports:
    - target: $RCT_HTTP_PORT
      published: $RCT_HTTP_PORT
    

    restart: "no"

  o2-rct_database:
    build: 
      target: development
    
    env_file:
    - ./docker/dev.env

    restart: "no"

networks:
  o2-rct_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.200.201.0/24"
          gateway: "172.200.201.1"