
services:
  o2-rct_application:
    container_name: o2-rct_application
    build: 
      target: development
    env_file:
    - ./docker/dev.env
    
    ports:
    - target: $RCT_HTTP_PORT
      published: $RCT_HTTP_PORT
    

    restart: "no"

  o2-rct_database:
    container_name: o2-rct_database
    build: 
      target: development
    
    env_file:
    - ./docker/dev.env

    restart: "no"