
services:
  o2-rct_application:
    build: 
      target: development
    env_file:
      - ./docker/env_file-dev

    volumes:
      - type: bind
        read_only: false
        source: ./
        target: /opt/RunConditionTable

    restart: "no"

  o2-rct_database:
    build: 
      target: development
    env_file:
      - ./docker/env_file-dev

    restart: "no"