
services:
  application:
    ports:
    - target: $RCT_HTTP_PORT
      published: $RCT_HTTP_PORT
      
    restart: "no"

  database:
    restart: "no"

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.200.201.0/24"
          gateway: "172.200.201.1"