
services:
  application:
    build: 
      target: test
    env_file:
      - ./docker/test.env
    volumes:
      - type: bind
        read_only: true
        source: ./security
        target: /opt/RunConditionTable/security
      - type: bind
        read_only: false
        source: ./database/cache
        target: /opt/RunConditionTable/database/cache
      - type: bind
        read_only: false
        source: ./reports
        target: /opt/RunConditionTable/reports
        
    restart: "no"

  database:
    build: 
      target: test
    env_file:
      - ./docker/test.env

    volumes:
    - type: bind
      read_only: true
      source: ./database
      target: /docker-entrypoint-initdb.d
    - type: bind
      read_only: false
      source: ./database/cache
      target: /postgres/run/database/cache

    
    restart: "no"

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.200.202.0/24"
          gateway: "172.200.202.1"