version: '3.1'
services:
  application:
    container_name: $APP_CONTAINER_NAME
    stdin_open: true
    tty: true 
    build:
      context: ./
      dockerfile: docker/application.dockerfile
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - network

  database:
    container_name: $DB_CONTAINER_NAME 
    build: 
      context: ./
      dockerfile: docker/database.dockerfile
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - network
  
      


