
services:
  application:
    build: 
      target: test
    env_file:
      - ./docker/env_fiel-test
    volumes:
      - type: bind
        read_only: false
        source: ./reports
        target: /opt/RunConditionTable/reports
        
    restart: "no"

  database:
    build: 
      target: test
    env_file:
      - ./docker/env_fiel-test

    
    restart: "no"