version: '3.1'
services:
  o2-rct_application:
    stdin_open: true
    tty: true 
    build:
      context: ./
      dockerfile: docker/application.dockerfile
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - o2-rct_network

  o2-rct_database:
    build: 
      context: ./
      dockerfile: docker/database.dockerfile
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - o2-rct_network

networks:
  o2-rct_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.200.200.0/24"
          gateway: "172.200.200.1"
      


