name: Tests

on: [push]

jobs:
  test:
    name: Tests on macos-latest
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - working-directory: ./app
      - run: (npm install)
      - run: (npm test)
    
