name: Tests

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    coverage:
        name: coverage
        runs-on: ubuntu-18.04
        defaults:
            run:
                working-directory: ./
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '16.14.x'
            - run: npm ci
            - run: npm run docker:test
            # - run: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
            - name: Send codecov report for RunConditionTable
              uses: codecov/codecov-action@v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: true

    static-analysis:
        runs-on: ubuntu-18.04
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 16.14.x
              uses: actions/setup-node@v2
              with:
                  node-version: '16.14.x'
            - name: Installing dependencies
              run: npm ci
            - name: Running static analysis
              run: npm run eslint
