name: Tests

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    coverage:
        name: coverage
        runs-on: ubuntu-18.04
        defaults:
            run:
                working-directory: ./
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '16.14.x'
            - run: npm ci
            - run: npm run docker:test
            # - run: ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
            - name: Send codecov report for RunConditionTable
              uses: codecov/codecov-action@v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  fail_ci_if_error: true

name: Lint

on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Install dependencies
              run: npm install
            - name: Run static analysis
              run: npm run eslint
